/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.Comp.ui.internal.CompActivator;

public class CompUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CompActivator.getInstance().getInjector("org.xtext.example.Comp");
	}

}
