FROM tomcat:8.0.20-jre8

RUN wget http://search.maven.org/remotecontent?filepath=com/netflix/eureka/eureka-server/1.8.7/eureka-server-1.8.7.war

RUN cp remotecontent?filepath=com%2Fnetflix%2Feureka%2Feureka-server%2F1.8.7%2Feureka-server-1.8.7.war ./webapps/eureka.war	

EXPOSE 80 8080