/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CompStandaloneSetup extends CompStandaloneSetupGenerated {

	def static void doSetup() {
		new CompStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
