/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.ui.AbstractCompUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CompUiModule extends AbstractCompUiModule {
  public CompUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
