/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.CompRuntimeModule;
import org.xtext.example.CompStandaloneSetup;
import org.xtext.example.ide.CompIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CompIdeSetup extends CompStandaloneSetup {
  @Override
  public Injector createInjector() {
    CompRuntimeModule _compRuntimeModule = new CompRuntimeModule();
    CompIdeModule _compIdeModule = new CompIdeModule();
    return Guice.createInjector(Modules2.mixin(_compRuntimeModule, _compIdeModule));
  }
}
